name: pynes # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Awesome and entertaining mine game # 79 char long summary
description: |
  Highly customizable and entertaining mine game

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: arm64
    run-on: all

apps:
  pynes:
    command: bin/pynes

parts:
  pynes:
    source: https://github.com/astraldev/pyne.git
    plugin: python
    requirements: ['requirements.txt']
    build-packages:
        - libcairo2-dev
        - libgirepository1.0-dev
        - gir1.2-gtk-3.0
        - libgtk-3-dev
        - pkg-config
    stage-packages:
        - libcairo-gobject2
        - libcairo2
        - libfontconfig1
        - libfreetype6
        - libgirepository-1.0-1
        - libpixman-1-0
