name: pynes # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Awesome and entertaining mine game # 79 char long summary
description: |
  Highly customizable and entertaining mine game

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: all

apps:
  pynes:
    command: bin/pynes

parts:
  pynes:
    source: .
    plugin: python
    requirements: requirements.txt
